# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webapigateway:
    image: webapigateway
    build:
      context: .
      dockerfile: microservices/webApiGateway/Dockerfile
    ports:
      - 7000:7000
    depends_on:
      - dummyservice
      - sigmacservice
  sigmacservice:
    image: sigmacservice
    build:
      context: .
      dockerfile: microservices/sigmacService/Dockerfile
  dummyservice:
    image: dummyservice
    build:
      context: .
      dockerfile: microservices/dummyService/Dockerfile