# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  pysigmaservice:
    image: pysigmaservice
    build:
      context: .
      dockerfile: microservices/pySigmaService/Dockerfile
    network_mode: host
